#!/bin/bash

set -ex

# have user root use fish as login shell
usermod --shell /bin/fish root

# create user "efly" with groups suggested in arch wiki:
# https://wiki.archlinux.org/title/users_and_groups#User_groups
# note: not creating home. it already exists in "img/extra/" and "/etc/skel" has already been copied.
useradd --no-create-home --groups adm,ftp,games,http,log,rfkill,sys,systemd-journal,uucp,wheel efly

# make sure efly home dir is actually owned by user efly
chown --recursive efly:efly /home/efly

# enable systemd services
systemctl enable NetworkManager.service
systemctl enable reflector.service
systemctl enable bluetooth.service

# install ymerge package manager
chown --recursive efly:efly /ymerge-PKGBUILD/
cd /ymerge-PKGBUILD/
sudo --user=efly makepkg --syncdeps --rmdeps --install --noconfirm --needed
cd /
rm -rf /ymerge-PKGBUILD/
