#!/bin/bash

set -ex

# TODO run these commands from efly-img and move it out of the profile
# register overlay partition in initcpio hook and growfs script
sed --in-place "s/XXX__EFLY_OVERLAY_UUID__XXX/${EFLY_OVERLAY_UUID}/g" /usr/lib/initcpio/hooks/overlayfs
sed --in-place "s/XXX__EFLY_OVERLAY_UUID__XXX/${EFLY_OVERLAY_UUID}/g" /etc/systemd/system/boot-growfs
# TODO can we put this into efly-img? it's not really an attribute of the profile...
# growable root partition is only available on live medium with persistent storage
if [[ $EFLY_MODE = "live-persistent" ]]
then
    systemctl enable boot-growfs.service
fi

# create user "efly" with groups suggested in arch wiki:
# https://wiki.archlinux.org/title/users_and_groups#User_groups
# note: not creating home. it already exists in "img/extra/" and "/etc/skel" has already been copied.
useradd --no-create-home --groups adm,ftp,games,http,log,rfkill,sys,systemd-journal,uucp,wheel efly

# make sure efly home dir is actually owned by user efly, which we are going to fix here.
chown --recursive efly:efly /home/efly

# enable systemd services
systemctl enable NetworkManager.service
systemctl enable reflector.service
systemctl enable bluetooth.service

# install ymerge package manager
chown --recursive efly:efly /ymerge-PKGBUILD/
cd /ymerge-PKGBUILD/
sudo --user=efly makepkg --syncdeps --rmdeps --install --noconfirm --needed
cd /
rm -rf /ymerge-PKGBUILD/
