#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# https://github.com/felixsinger/mkinitcpio-overlayfs/blob/master/mkinitcpio-overlayfs.hook

ROOT_MNT="/new_root"
OFS_DIRS="/run/archroot"
OFS_LOWER="${OFS_DIRS}/root_ro"
OFS_COWSPACE="${OFS_DIRS}/cowspace"
OFS_UPPER="${OFS_COWSPACE}/upper"
OFS_WORK="${OFS_COWSPACE}/work"

run_latehook() {
	[ -d ${OFS_LOWER} ] || mkdir -p ${OFS_LOWER}
	mount --move ${ROOT_MNT} ${OFS_LOWER}

	mkdir -p ${OFS_COWSPACE}

	# uncomment this if you want non-persistent memory with filesystem in RAM.
	# mount -t tmpfs cowspace ${OFS_COWSPACE}

	# uncomment this if you want persistent storage
	# TODO replace this with UUID or label instead of /dev/sda3
	# mount /dev/sda3 ${OFS_COWSPACE}
	mount PARTLABEL="efly-overlay" ${OFS_COWSPACE}

	[ -d ${OFS_UPPER} ] || mkdir -p ${OFS_UPPER}
	[ -d ${OFS_WORK} ] || mkdir -p ${OFS_WORK}

	mount -t overlay -o lowerdir=${OFS_LOWER},upperdir=${OFS_UPPER},workdir=${OFS_WORK} rootfs ${ROOT_MNT}
}
