name: build-img

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build IMG File
        run: |
          sudo bash ci/build-img.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            efly-live.img
