name: build-release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ISO File
        run: |
          sudo bash scripts/build-release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            efly-live.iso
            efly-live.iso.b2sum
