#!/usr/bin/python3
# TODO add --version flag

from elib import version

usage = f"""
Usage: efly [subcommand] [options]
       efly <subcommand> --help

Version: {version}

Create and manage bootable disk images based on Arch Linux.

Subcommands:
  efly dd        :: Install efly on a given block device.
  efly qemu      :: Boot a disk image using qemu.
  efly reflector :: Update pacman mirror list.
  efly vncserver :: Launch a VNC server using TigerVNC.
""".lstrip().rstrip()

import os, sys, subprocess
from pathlib import Path

script_dir = Path(os.path.dirname(os.path.realpath(__file__)))

# print usage and exit on empty input
if len(sys.argv) == 1 or sys.argv[1] == "-h" or sys.argv[1] == "--help":
    print(usage)
    exit(0)

cmd = sys.argv[1]
args = sys.argv[2:]
if cmd == "dd" or cmd == "qemu" or cmd == "reflector" or cmd == "vncserver":
    completed_process = subprocess.run([script_dir / f"efly-{cmd}"] + args)
    exit(completed_process.returncode)
else:
    print(f'[error] unknown subcommand "{cmd}". run "efly --help" to see available subcommands.')
    exit(1)
